### ISSUE TITLE
'net.tetrakoopa.shell-package' plugin not found

### ISSUE THREAD

**Issue by aleksficek** [martin-der/gradle-shell-plugin#2]
Trying to use this plugin but keep getting `Plugin with id 'net.tetrakoopa.shell-package' not found.`

Have tried following the setup instructions exactly and also several deviations but to no avail. Would appreciate if I could get a confirmation that this issue exists with others or if there is any solution to it.

Thanks!

**Comment by martin-der** [comment]
This is indeed a bug.
I have a lot of uncommited/pushed changes in my local repository, sleeping for a long time.
This is a old project that did the job for me and I did not bother to push everything back then on Github.

I'm going to fix this anyway. I hope you did not waste too much time on this.

At first glance the doc is missing the declaration of build scripts dependencies. There should be at least the declaration of the plugin jar.

~~~groovy
buildscript{
	repositories{
		maven { url 'https://jitpack.io' }
	}

	dependencies {
		// this is missing :
		classpath "com.github.martin-der.gradle-shell-plugin:shell:v0.1-beta-8"
	}
}
~~~

You can give a try but there is so many changes in my local repository that you may face more issues after.

I'll push the latest changes as soon as possible.

**Comment by aleksficek** [comment]
Thanks for the fast response! Your solution fixed the issue but as you mentioned I ran into another issue soon after (not sure if there's a quick fix for this one): 
```
Execution failed for task ':installer'.
> A problem occurred starting process 'command 'shar''
```

Really looking forward to seeing the plugin updated and working, would love to utilize it in https://rapids.ai/

**Comment by martin-der** [comment]
This another information missing in the documentation, sorry.
On needs `shar` ( from the `sharutils` package - as it is named in debian based distributions ) in order to create a self-extracting shell archive.

> Really looking forward to seeing the plugin updated and working

I'd be glad if this project was usefull to someone else.
Let me dive into it's code. I'm bit rusty when it comes to this gradle-plugin.

I'll push the changes as soon as they are tested and I have checked the configuration. If I recall correcly the configuration have **really slightly** changed.
Also a quick doc generation from comment was added ( it requires the `gawk` command ).

**Comment by martin-der** [comment]
I pushed a v0.1RC2 version on master.
Let me now if it works for you.
...and also, assuming it does, if it overall fits your needs.

**Comment by aleksficek** [comment]
Sweet, thanks for this. I'll be implementing the plugin in the next few days, I'll keep you posted but this is great!

**Comment by aleksficek** [comment]
Hey Martin, I managed to successfully execute `gradle shell-test` but unfortunately am still having issues with `gradle shell-build`/`gradle package`. I've also installed `sharutils` locally as you suggested but have the following issue with both shell-build and package commands:

```
> Configure project :
Evaluating root project 'seed-job-dsl' using build file 'pathtoproject/seed-job-dsl/build.gradle'.
Starting process 'command 'chmod''. Working directory: pathtoproject/seed-job-dsl Command: chmod +x pathtoproject/seed-job-dsl/build/n4k-shell/installer/seed-job-dsl-unspecified.shar
Successfully started process 'command 'chmod''
chmod: cannot access 'pathtoproject/seed-job-dsl/build/n4k-shell/installer/seed-job-dsl-unspecified.shar': No such file or directory

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'seed-job-dsl'.
> Process 'command 'chmod'' finished with non-zero exit value 1
```

Appreciate the updates and help!

**Comment by martin-der** [comment]
Hi Aleksander,
I'm having hard time reproducing the problem.

Could you try a few things :

- adding `makeExecutable = false` in installer configuration
~~~groovy
shell_package {
	installer {
		// This is a configuration to prevent adjunction of the executable bit to generated installer
		// It should be off by default though...
		makeExecutable = false
	}
}
~~~
- adding a `version` to your project : `version 1.2.3`

Please list what's in your project `build/n4k-shell/installer`.
Or, at least, tell me if there is anything like `*.shar`.


Just to make sure : are you using v0.1.2 version ?
or the current master (sha1:e1c531749a072ab4af406f71481609d9b1454659) ?
I not could you do so please ?
[edit] changed the latest version in the README [/edit]


If I can't pinpoint the issue I might need the build.gradle  and the files in your `seed-job-dsl` project ( empty files with the same folder hierarchy will be just fine !).

**Comment by aleksficek** [comment]
Hey Martin, the version change did the trick! Thanks for the help and the plugin, it's been great using it so far!

**Comment by martin-der** [comment]
That's good to know it helped you!
Im closing this issue.

Feel free to open issue/improvement. I'm not fully dedicated to this project and my time I way more limited than when I started it but I'll do my best.
